### ISSUE TITLE
AGM on 25th January 2017

### ISSUE THREAD

**Issue by ereeshika** [fossnsbm/2k17-objectives#27]
Need to make a Schedule and Assign tasks to current members asap.

**Comment by ereeshika** [comment]
1. Small intro to waffle @Rajithkonara I think you can do this
2. Introducing Big Brother Big Sister Program @rav94  can you?
3. Forming up small teams for better management I'll do my best to handle this
4. Mentor Speech by Mr.Chaminda Wijesinghe
5. Entertainment item Prageeth Rajapakshe will handle that
6. Introducing  NSBM OS @Silentk94 all yours to handle

**Comment by rav94** [comment]
@AmilaE ok! Will talk to you!

**Comment by Ruwan-Ranganath** [comment]
25th Plan ?

**Comment by BhagyaR94** [comment]
Thank you @AmilaE, I'm working on it...

**Comment by Ruwan-Ranganath** [comment]
each assignee please  update what your plan/ slides / as a comment before 20th . 
also assign someone to talk about IEEE, we need to establish IEEE branch within next month ? anyone who think handle this please assign task 24 to you.

**Comment by Rajithkonara** [comment]
@AmilaE i'll do it. @Ruwan-Ranganath i created this slides for a webinar I think it's fine 
(https://docs.google.com/presentation/d/1mmF43co2X2GR6yNhOvuwCT6AyxpT2KuBEwDz0l8Wqgw/edit?usp=sharing)

**Comment by Rajithkonara** [comment]
A little introduction blog post on waffle and github issues (https://rkdevblog.wordpress.com/2017/01/16/introduction-to-waffle-and-github-issues/ )
