### ISSUE TITLE
How to work with waffle & github issues

### ISSUE THREAD

**Issue by Ruwan-Ranganath** [fossnsbm/2k17-objectives#7]
Add others people to the organization . 
We will have a  team call to KT how to use waffle and github issue to follow up progress.

**Comment by Rajithkonara** [comment]
priority-1 @AmilaE @Ruwan-Ranganath can we do it tonight

**Comment by Ruwan-Ranganath** [comment]
@Rajithkonara can you takeover ? 
I won't be able to connect tonight.

**Comment by Rajithkonara** [comment]
@Ruwan-Ranganath ok :)

**Comment by Ruwan-Ranganath** [comment]
Topics to cover today .
Please make sure all the active members ( + new members ) attend to this webinar . 

- [ ] Why use github issue to track objective progress
- [ ] Introduce waffle and connection to github issues -> [https://waffle.io/fossnsbm/2k17-objectives](https://waffle.io/fossnsbm/2k17-objectives)
- [ ] Introduce Labels ->  [https://github.com/fossnsbm/2k17-objectives/labels](https://github.com/fossnsbm/2k17-objectives/labels)
- [ ] Demo on adding issue on waffle -> assign member -> labeling -> changing waffle backlog/on progress / done / ready  Cards. 

Anything to add apart from above checklist ?

**Comment by Rajithkonara** [comment]
I think all are covered here @AmilaE can you set a date, problem is no new members are there still. ???

**Comment by ereeshika** [comment]
@Rajithkonara and @Ruwan-Ranganath The issue is that the email hasn't been sent yet. @lasithatharanga  Please send the email to the people list of people who are already on the list updated by @Silentk94 . We can send the rest as the second wave after Hashi has sent her list.

**Comment by ereeshika** [comment]
And the most common issue would be that most of people aren't familiar with waffle.io yet. So we have to be patient till we hold a meeting and give a small demo to the new guys to how to use and collaborate with this. So we must focus on the AGM.

**Comment by lasithatharanga** [comment]
@AmilaE  Done

**Comment by Ruwan-Ranganath** [comment]
can we finalize the dates ?
also please send this link to the new members , so they can track the changes .

**Comment by Rajithkonara** [comment]
@Ruwan-Ranganath (https://docs.google.com/presentation/d/1mmF43co2X2GR6yNhOvuwCT6AyxpT2KuBEwDz0l8Wqgw/edit?usp=sharing) is this enough ? anything to add ?

**Comment by Ruwan-Ranganath** [comment]
I guess thats a  go !

**Comment by BhagyaR94** [comment]
Okay for me.I have a suggestion too, How about we explain the "Demo" topics in one line? I believe that'll give a better picture.

**Comment by Rajithkonara** [comment]
Fine by me @Silentk94  do the changes. Like @Ruwan-Ranganath said will do a live stream

**Comment by BhagyaR94** [comment]
Okay....
are we doing it in sinhala?

**Comment by ereeshika** [comment]
@Silentk94 Most people will understand in Sinhala. But there are several people who can't. i think you remember some of them at our last event.
